"""
Export service.

Renders an already-computed repository analysis (overview + analytics,
optionally with an AI summary) into a Markdown report. PDF rendering is
layered on top of the same Markdown in app/services/pdf_service.py so the
two formats never drift apart.
"""
from __future__ import annotations

from datetime import datetime, timezone

from app.schemas.ai import AISummary
from app.schemas.analytics import RepositoryAnalytics
from app.schemas.repository import RepositoryOverview


def build_markdown_report(
    repo: RepositoryOverview,
    analytics: RepositoryAnalytics,
    ai_summary: AISummary | None = None,
) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []

    lines.append(f"# Repository Health Report — {repo.full_name}")
    lines.append("")
    lines.append(f"Generated {generated_at} by GitHub Repository Intelligence.")
    if repo.description:
        lines.append("")
        lines.append(f"> {repo.description}")
    lines.append("")
    lines.append(f"**Repository:** {repo.html_url}")
    lines.append("")

    lines.append("## Health Score")
    lines.append("")
    lines.append(f"**{analytics.health.overall}/100 — {analytics.health.label}**")
    lines.append("")
    lines.append(f"_{analytics.health.methodology}_")
    lines.append("")
    lines.append("| Factor | Score | Notes |")
    lines.append("|---|---|---|")
    for factor in analytics.health.factors:
        lines.append(f"| {factor.name} | {factor.score}/100 | {factor.explanation} |")
    lines.append("")

    lines.append("## Engineering Metrics")
    lines.append("")
    metrics = analytics.metrics
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(
        f"| Issue resolution rate | "
        f"{metrics.issue_resolution_rate if metrics.issue_resolution_rate is not None else 'N/A'}% |"
    )
    lines.append(
        f"| PR merge rate | "
        f"{metrics.pr_merge_rate if metrics.pr_merge_rate is not None else 'N/A'}% |"
    )
    lines.append(
        f"| Release frequency | "
        f"{metrics.release_frequency_days if metrics.release_frequency_days is not None else 'N/A'} days |"
    )
    lines.append(
        f"| Bus factor | "
        f"{metrics.bus_factor if metrics.bus_factor is not None else 'N/A'} |"
    )
    if metrics.is_estimate:
        lines.append("")
        lines.append("_Metrics marked above are estimates derived from sampled GitHub data._")
    lines.append("")

    if ai_summary:
        lines.append("## AI Summary")
        lines.append("")
        lines.append(ai_summary.summary)
        lines.append("")
        if ai_summary.strengths:
            lines.append("**Strengths**")
            lines.append("")
            for item in ai_summary.strengths:
                lines.append(f"- {item}")
            lines.append("")
        if ai_summary.risks:
            lines.append("**Risks**")
            lines.append("")
            for item in ai_summary.risks:
                lines.append(f"- {item}")
            lines.append("")
        if ai_summary.recommendations:
            lines.append("**Recommendations**")
            lines.append("")
            for item in ai_summary.recommendations:
                lines.append(f"- {item}")
            lines.append("")

    lines.append("## Recent Activity")
    lines.append("")
    if analytics.activity:
        for event in analytics.activity[:15]:
            link = f" — [{event.label}]({event.url})" if event.url else f" — {event.label}"
            lines.append(f"- `{event.occurred_at}` {event.kind}{link}")
    else:
        lines.append("_No recent activity found._")
    lines.append("")

    lines.append("---")
    lines.append("_Report generated by GitHub Repository Intelligence — "
                  "https://github-intelligence-nine.vercel.app_")

    return "\n".join(lines)
